config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :users do
  	collection do
  		get 'search'
  	end
    get '/interests', to: 'users#interests'
    get '/resume', to: 'users#resume'
  end

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  searchkick
  def to_param
  	fullname
  end

  before_create :create_login

  def create_login
    self.fullname = "#{firstname}#{lastname}"
  end


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_attached_file :image, styles: { medium: "400x600#", thumb: "100x100#", small: "200x300#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/


  has_attached_file :document, styles: {thumbnail: "60x60#"}
  validates_attachment :document, content_type: { content_type: "application/pdf" }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
    def configure_sign_up_params
      devise_parameter_sanitizer.for(:sign_up) << :image << :document << :interests << :firstname << :lastname << :fullname
    end

  # You can put the params you want to permit in the empty array.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :image << :document << :interests << :firstname << :lastname << :fullname
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before_action :authenticate_user!
	
	def index
		#@users = User.all
		@users = User.where.not(id: current_user).order("RANDOM()").limit(3)
	end

	def show
    	@user = User.find_by_fullname(params[:id])
  end
  def interests
    	@user = User.find_by_fullname(params[:user_id])
  end
  def resume
    	@user = User.find_by_fullname(params[:user_id])
  end
  def search
    if params[:search].present?
      @users = User.search(params[:search])
    else
      @users = User.all
    end
  end
end

#a change

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Professional Portfolios", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      <%= form_tag search_users_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Professional Portfolios</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/users/_form.html.erb
      				<%= image_tag @user.image.url(:medium) %>
      				<table class="table">
 						<tbody>
 							<tr>  
 								<td><strong>Full Name:</strong></td>
           		 				<td><%= @user.firstname %> <%= @user.lastname %></td>
       		 				</tr>
							<tr>
								<td><strong>Email:</strong></td>
								<td><%= @user.email %></td>
							</tr>
							<tr>
								<td><strong>Interests:</strong></td>
								<td><%= link_to 'Interests', url_for(@user)+"/interests" %></td>
							</tr>
							<tr>
								<td><strong>Resume:</strong></td>
								<td><%= link_to 'Resume', url_for(@user)+"/resume" %></td>
							</tr>
    					</tbody>
					</table>

app/views/users/index.html.erb
	<% if @users %>
      					<table class="table">
 							<tbody>
 								<% @users.each do |user| %>
 								<td>
 									<table>
 										<tbody>
  										<tr>
  										<td><%= link_to (image_tag user.image.url(:small), class: 'image'), user %></td>
  										</tr>
  										<tr>
  										<td><%= user.email %></td>
  										</tr>
  										<tr>
  										<td><%= user.fullname %></td>
  										</tr>
      									<tr>
      									<td><%= link_to 'See Profile', user_path(user) %></td>
      									</tr>
      									</tbody>
      								</table>
      							</td>
      							<% end %>
							</tbody>
						</table>
	<% end %>

app/views/users/interests.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
      		<div class="col-md-4">
      			<table class="table">
 					<tbody>
 						<tr>
							<td><%= @user.interests %></td>
						</tr>
						<tr>
							<td><%= link_to('Back', @user) %></td>
						</tr>
					</tbody>
			</div>
		</div>
	</div>
</div>

app/views/users/resume.html.erb
 <div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
      		<div class="col-md-4">
      			<object width="1000" height="800" data= <%= @user.document.url() %>></object>
      			<table class="table">
 					<tbody>
						<tr>
							<%= link_to('Back', @user) %>
						</tr>
					</tbody>
			</div>
		</div>
	</div>
</div>

app/views/users/search.html.erb
<div class="row">
  <% @users.each do |user| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag user.image.url(:medium), class: 'image'), user %>
        <%= user.email %>
        <br>
  		<%= user.fullname %>
  		<br>
      	<%= link_to 'See Profile', user_path(user) %>
      	<br>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
      		<div class="col-md-4">
      			<%= render 'form' %>
			</div>
		</div>
	</div>
</div>